#!/bin/bash

# This bash script is highly tailored to GPS FILES produced by the AMOD AGL3080 GPS tracker. 
# It checks that the given filename contains at most one 'STRING_TO_CHECK' specified below.
# Example outputs:
#	$ check_combined_amod_tracks fail.log 
#	Checking 'fail.log'...:FAILED!
#	 ---> Failure Reason: File 'fail.log' does not contain at most one string '$ADVER,3080,2.3'
#
#	$ check_combined_amod_tracks GPS_Florida.log 
#	Checking 'GPS_Florida.log'...:OK

FILENAME=$1
STRING_TO_CHECK='$ADVER,3080,2.3'

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 filename"
    exit -1
fi

if [ ! -f $OUTFILE ];
then
	echo -e "File $OUTFILE does not exists. Aborting..."
	exit 1
fi

echo -n "Checking '$FILENAME'...:"
if [ $(cat "$FILENAME" | grep "$STRING_TO_CHECK" | wc -l) -le "1" ];
then
	echo "OK"
else
	echo "FAILED!"
	echo " ---> Failure Reason: File '$FILENAME' does not contain at most one string '$STRING_TO_CHECK'"
fi
