#!/bin/bash

# This bash script is highly tailored to GPS files produced by the AMOD AGL3080 GPS tracker. 
#
# This script copies all files matching the 'FILE_PATTERN_REGEX' below from the given
# 'INPUT_DIR' to the given 'OUTPUT_DIR'.
# Example output:
#	$ collect_all_daily_amod_tracks

FILE_PATTERN_REGEX='.*GPS_[^_]+\.log'
INPUT_DIR=$1
OUTPUT_DIR=$2

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 inputdir outputdir"
    exit -1
fi
if [ ! -d "$INPUT_DIR" ];
then
	echo -e "Input directory $INPUT_DIR does not exist. Aborting..."
	exit 1
fi
if [ ! -d "$OUTPUT_DIR" ];
then
	echo -e "Input directory $OUTPUT_DIR does not exist. Aborting..."
	exit 1
fi

find -E "$INPUT_DIR" -regex $FILE_PATTERN_REGEX -type f -not -path "$(pwd $OUTPUT_DIR)/$OUTPUT_DIR" -exec cp -npv {} "$OUTPUT_DIR" \;
